[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "superfluid-finance/=lib/protocol-monorepo/",
    "@superfluid-finance/ethereum-contracts/=lib/protocol-monorepo/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

